# Site settings
title: Al-Kitaab and Sunnah Publications
email: info@kspublications.com
description: "Books by Muhammad Jibaly published by Al-Kitaab and Sunnah Publications."
baseurl: ""
url: "http://kspublications.com"

# Build settings
markdown: kramdown
permalink: pretty

collections:
  ref:
    output: true

defaults:
  - scope:
      type: ref
    values:
      layout: ref
